#ifndef _PARTITION_PSC3_P8_H_
#define _PARTITION_PSC3_P8_H_

#include "cy_device_headers.h"
#include "cymem_CM33_0_S.h"

#define MMIO_NS_START               0x42000000
#define MMIO_S_START                0x52000000
#define MMIO_SIZE                   0x02000000
#define FLASH_NSC_SIZE              0x00000100
#if (CY_PDL_FLASH_BOOT)
#define SRAM0_NSC_SIZE              0x00000000
#else
#define SRAM0_NSC_SIZE              0x00000800
#endif

/** Flash memory regions generated by the Device Configurator memory personality. */
#define FLASH_NS_SAHB_START         (CYMEM_CM33_0_S_m33s_nvm_START)
#define FLASH_S_SAHB_START          (CYMEM_CM33_0_S_m33s_nvm_S_START)
#define FLASH_NS_CBUS_START         (CYMEM_CM33_0_S_m33s_nvm_C_START)
#define FLASH_S_CBUS_START          (CYMEM_CM33_0_S_m33s_nvm_C_S_START)
#define FLASH_SIZE                  (CY_FLASH_SIZE)
#define FLASH_S_SIZE                (CYMEM_CM33_0_S_m33s_nvm_SIZE)

#if defined(CYMEM_CM33_0_S_m33ns_nvm_START)
#define FLASH_NS_SAHB_CODE_START    (CYMEM_CM33_0_S_m33ns_nvm_START)
#define FLASH_NS_CBUS_CODE_START    (CYMEM_CM33_0_S_m33ns_nvm_C_START)
#define FLASH_NS_OFFSET             (CYMEM_CM33_0_S_m33ns_nvm_OFFSET)
#define FLASH_NS_SIZE               (CYMEM_CM33_0_S_m33ns_nvm_SIZE)
#define FLASH_NS_SBUS_SAU_START     (CYMEM_CM33_0_S_m33ns_nvm_START)
#define FLASH_NS_SBUS_SAU_END       (CYMEM_CM33_0_S_m33ns_nvm_START + CYMEM_CM33_0_S_m33ns_nvm_SIZE)
#define FLASH_NS_CBUS_SAU_START     (CYMEM_CM33_0_S_m33ns_nvm_C_START)
#define FLASH_NS_CBUS_SAU_END       (CYMEM_CM33_0_S_m33ns_nvm_C_START + CYMEM_CM33_0_S_m33ns_nvm_SIZE)
#else
#define FLASH_NS_SAHB_CODE_START    (CYMEM_CM33_0_S_m33s_ppca0_nvm_START)
#define FLASH_NS_CBUS_CODE_START    (CYMEM_CM33_0_S_m33s_ppca0_nvm_C_START)
#define FLASH_NS_OFFSET             (CYMEM_CM33_0_S_m33s_ppca0_nvm_OFFSET)
#define FLASH_NS_SIZE               (CYMEM_CM33_0_S_m33s_ppca0_nvm_SIZE + CYMEM_CM33_0_S_m33s_ppca1_nvm_SIZE)
#define FLASH_NS_SBUS_SAU_START     (CYMEM_CM33_0_S_m33s_ppca0_nvm_START)
#define FLASH_NS_SBUS_SAU_END       (CYMEM_CM33_0_S_m33s_ppca1_nvm_START + CYMEM_CM33_0_S_m33s_ppca1_nvm_SIZE)
#define FLASH_NS_CBUS_SAU_START     (CYMEM_CM33_0_S_m33s_ppca0_nvm_C_START)
#define FLASH_NS_CBUS_SAU_END       (CYMEM_CM33_0_S_m33s_ppca1_nvm_C_START + CYMEM_CM33_0_S_m33s_ppca1_nvm_SIZE)
#endif

/** SRAM regions generated by the Device Configurator memory personality. */
#define SRAM0_NS_SAHB_START         (CYMEM_CM33_0_S_m33s_shared_START)
#define SRAM0_S_SAHB_START          (CYMEM_CM33_0_S_m33s_shared_S_START)
#define SRAM0_NS_CBUS_START         (CYMEM_CM33_0_S_m33s_shared_C_START)
#define SRAM0_S_CBUS_START          (CYMEM_CM33_0_S_m33s_shared_C_S_START)
#define SRAM0_S_CBUS_CODE_START     (CYMEM_CM33_0_S_m33s_shared_C_S_START)
#define SRAM0_S_SIZE                (CYMEM_CM33_0_S_m33s_shared_SIZE + CYMEM_CM33_0_S_m33s_data_SIZE)
#define SRAM0_SHM_SIZE              (CYMEM_CM33_0_S_m33s_shm_data_SIZE)
#define SRAM0_SHM_S_SIZE            (CYMEM_CM33_0_S_m33s_shm_data_SIZE)
#define SRAM0_SHM_NS_SIZE           (CYMEM_CM33_0_S_m33s_shm_data_SIZE)

#if defined(CYMEM_CM33_0_S_m33ns_data_START)
#define SRAM0_NS_SIZE               (CYMEM_CM33_0_S_m33ns_data_SIZE)
#define SRAM0_NS_OFFSET             (CYMEM_CM33_0_S_m33ns_data_OFFSET)
#define SRAM0_SHM_OFFSET            (CYMEM_CM33_0_S_m33ns_data_OFFSET + CYMEM_CM33_0_S_m33ns_data_SIZE)
#define SRAM0_NSC_OFFSET            (SRAM0_SHM_OFFSET + CYMEM_CM33_0_S_m33s_shm_data_SIZE)
#define SRAM0_NS_CBUS_CODE_START    (CYMEM_CM33_0_S_m33ns_data_C_START)
#define SRAM0_NS_SBUS_SAU_START     (CYMEM_CM33_0_S_m33ns_data_START)
#define SRAM0_NS_SBUS_SAU_END       (CYMEM_CM33_0_S_m33ns_data_START + CYMEM_CM33_0_S_m33ns_data_SIZE + CYMEM_CM33_0_S_m33s_shm_data_SIZE - SRAM0_NSC_SIZE)
#define SRAM0_NS_CBUS_SAU_START     (CYMEM_CM33_0_S_m33ns_data_C_START)
#define SRAM0_NS_CBUS_SAU_END       (CYMEM_CM33_0_S_m33ns_data_C_START + CYMEM_CM33_0_S_m33ns_data_SIZE + CYMEM_CM33_0_S_m33s_shm_data_SIZE - SRAM0_NSC_SIZE)
#else
#define SRAM0_NS_SIZE               (CYMEM_CM33_0_S_m33s_shm_data_SIZE)
#define SRAM0_NS_OFFSET             (CYMEM_CM33_0_S_m33s_shm_data_OFFSET)
#define SRAM0_SHM_OFFSET            (CYMEM_CM33_0_S_m33s_shm_data_OFFSET)
#define SRAM0_NSC_OFFSET            (CYMEM_CM33_0_S_m33s_shm_data_OFFSET + CYMEM_CM33_0_S_m33s_shm_data_SIZE)
#define SRAM0_NS_CBUS_CODE_START    (CYMEM_CM33_0_S_m33s_shm_data_C_START)
#define SRAM0_NS_SBUS_SAU_START     (CYMEM_CM33_0_S_m33s_shm_data_START)
#define SRAM0_NS_SBUS_SAU_END       (CYMEM_CM33_0_S_m33s_shm_data_START + CYMEM_CM33_0_S_m33s_shm_data_SIZE - SRAM0_NSC_SIZE)
#define SRAM0_NS_CBUS_SAU_START     (CYMEM_CM33_0_S_m33s_shm_data_C_START)
#define SRAM0_NS_CBUS_SAU_END       (CYMEM_CM33_0_S_m33s_shm_data_C_START + CYMEM_CM33_0_S_m33s_shm_data_SIZE - SRAM0_NSC_SIZE)
#endif

#define SRAM0_SIZE                  (SRAM0_S_SIZE + SRAM0_NS_SIZE + SRAM0_SHM_SIZE + SRAM0_NSC_SIZE)
#define SRAM1_SIZE                  (0x00000000)
#define SRAM_SIZE                   (SRAM0_SIZE + SRAM1_SIZE)

#define SRAM0_S_SAHB_SHARED_START   (CYMEM_CM33_0_S_m33s_shm_data_S_START)
#define SRAM0_S_CBUS_SHARED_START   (CYMEM_CM33_0_S_m33s_shm_data_C_S_START)
#define SRAM0_NS_SAHB_SHARED_START  (CYMEM_CM33_0_S_m33s_shm_data_START)
#define SRAM0_NS_CBUS_SHARED_START  (CYMEM_CM33_0_S_m33s_shm_data_C_START)

/** SAU regions */
#define MMIO_NS_SAU_START           (MMIO_NS_START)
#define MMIO_NS_SAU_END             (MMIO_NS_START + MMIO_SIZE)
#if (CY_PDL_FLASH_BOOT)
#define NS_BOOT_START               (FLASH_NS_CBUS_CODE_START)
#else
#define NS_BOOT_START               (SRAM0_NS_CBUS_CODE_START)
#endif

/* Dynamic NSC SAU region - uses linker-provided symbols for correct NSC placement */
#if defined(__ARMCC_VERSION)
extern uint32_t Image$$app_codeNsc$$Base;
extern uint32_t Image$$app_codeNsc$$Length;
#define NSC_SAU_START               ((uint32_t)&Image$$app_codeNsc$$Base)
#define NSC_SAU_END                 ((uint32_t)&Image$$app_codeNsc$$Base + (uint32_t)&Image$$app_codeNsc$$Length)
#elif defined(__GNUC__) || defined(__llvm__)
extern uint32_t __nsc_region_start;
extern uint32_t __nsc_region_size;
#define NSC_SAU_START               ((uint32_t)&__nsc_region_start)
#define NSC_SAU_END                 ((uint32_t)&__nsc_region_start + (uint32_t)&__nsc_region_size)
#elif defined(__ICCARM__)
#pragma section = "NSC"
#define NSC_SAU_START               ((uint32_t)__section_begin("NSC"))
#define NSC_SAU_END                 ((uint32_t)__section_begin("NSC") + (uint32_t)__section_size("NSC"))
#endif

#endif /* _PARTITION_PSC3_P8_H_ */
